name: random-1on1-questions-action
description: "Posts a comment with a list of randomly selected 1-on-1 questions when a new issue matches a specific label"
author: Pierluigi Cau

branding:
  icon: help-circle
  color: green

inputs:
  num-categories:
    description: "Desired quantity of question categories"
    required: true
    default: "3"
  num-questions:
    description: "Number of questions to be generated per category"
    required: true
    default: "1"
  label:
    description: "The label to trigger this workflow"
    required: true
    default: "1on1"
  issue-number:
    description: "(Optional) the issue number to fetch if responding to a different event"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
