name: Weekly one to one
on:
  #schedule:
  #- cron: 0 12 * * 7  # Every sunday at noon – https://crontab.guru
  push # for tests
      

jobs:
  weekly_meeting:
    name: create new issue
    runs-on: ubuntu-latest
    steps:

    # Repo code checkout required if `template` is used
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: issue-bot
      id: issue-bot
      uses: imjohnbo/issue-bot@v2
      with:
        assignees: "pierluigi" # GitHub handles without the @
        labels: "1on1"
        pinned: true
        close-previous: true
        template: ".github/ISSUE_TEMPLATE/one-to-one.md" # assignees, labels will be overridden if present in YAML header
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate random questions
      uses: ./
      with:
        issue-number: ${{ steps.issue-bot.outputs.issue-number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Optional: ovverride these defaults
        # num-categories: "3" # how many question categories
        # num-questions: "1" # how many questions per category
        # label: "1on1" # which label triggers this workflow

